### PR TITLE
#165597004 Add "isBookmarked" to response for endpoint for getting a single article

### PR DESCRIPTION
**Pull request by danprocoder**
#### What does this PR do?
Add property to tell if article is bookmarked to response from endpoint to get single article.

#### Description of Task to be completed?
- Add property to tell if article is bookmarked to response from endpoint to get single article.

#### How should this be manually tested?
1. Clone this branch.
2. Run `npm install` to install the dependencies.
3. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#165597004](https://pivotaltracker.com/story/show/165597004)

### CODE REVIEW

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by shaolinmkz — COMMENTED** [review]
REVIEWED

**Review by Dsalz — COMMENTED** [review]
LGTM

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
